rm -fr SIG
mkdir SIG
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/T2tt_400_320_treeProducerSusyMultilepton_tree.root -ofile=SIG/T2tt_400_320.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/T2tt_400_330_treeProducerSusyMultilepton_tree.root -ofile=SIG/T2tt_400_330.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/T2tt_400_340_treeProducerSusyMultilepton_tree.root -ofile=SIG/T2tt_400_340.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/T2tt_400_350_treeProducerSusyMultilepton_tree.root -ofile=SIG/T2tt_400_350.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/T2tt_400_360_treeProducerSusyMultilepton_tree.root -ofile=SIG/T2tt_400_360.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/T2tt_400_370_treeProducerSusyMultilepton_tree.root -ofile=SIG/T2tt_400_370.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/T2tt_400_380_treeProducerSusyMultilepton_tree.root -ofile=SIG/T2tt_400_380.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/T2tt_400_390_treeProducerSusyMultilepton_tree.root -ofile=SIG/T2tt_400_390.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/T2tt_500_420_treeProducerSusyMultilepton_tree.root -ofile=SIG/T2tt_400_420.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/T2tt_500_430_treeProducerSusyMultilepton_tree.root -ofile=SIG/T2tt_500_430.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/T2tt_500_440_treeProducerSusyMultilepton_tree.root -ofile=SIG/T2tt_500_440.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/T2tt_500_450_treeProducerSusyMultilepton_tree.root -ofile=SIG/T2tt_500_450.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/T2tt_500_460_treeProducerSusyMultilepton_tree.root -ofile=SIG/T2tt_500_460.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/T2tt_500_470_treeProducerSusyMultilepton_tree.root -ofile=SIG/T2tt_500_470.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/T2tt_500_480_treeProducerSusyMultilepton_tree.root -ofile=SIG/T2tt_500_480.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/T2tt_500_490_treeProducerSusyMultilepton_tree.root -ofile=SIG/T2tt_500_490.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/T2tt_600_520_treeProducerSusyMultilepton_tree.root -ofile=SIG/T2tt_600_520.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/T2tt_600_530_treeProducerSusyMultilepton_tree.root -ofile=SIG/T2tt_600_530.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/T2tt_600_540_treeProducerSusyMultilepton_tree.root -ofile=SIG/T2tt_600_540.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/T2tt_600_550_treeProducerSusyMultilepton_tree.root -ofile=SIG/T2tt_600_550.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/T2tt_600_560_treeProducerSusyMultilepton_tree.root -ofile=SIG/T2tt_600_560.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/T2tt_600_570_treeProducerSusyMultilepton_tree.root -ofile=SIG/T2tt_600_570.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/T2tt_600_580_treeProducerSusyMultilepton_tree.root -ofile=SIG/T2tt_600_580.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/T2tt_600_590_treeProducerSusyMultilepton_tree.root -ofile=SIG/T2tt_600_590.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_200_100_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_200_100.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_200_110_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_200_110.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_200_120_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_200_120.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_200_130_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_200_130.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_200_140_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_200_140.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_200_150_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_200_150.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_200_160_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_200_160.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_200_170_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_200_170.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_200_180_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_200_180.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_200_185_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_200_185.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_200_190_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_200_190.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_200_193_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_200_193.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_200_1_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_200_1.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_200_25_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_200_25.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_200_50_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_200_50.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_200_60_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_200_60.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_200_70_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_200_70.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_200_80_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_200_80.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_200_90_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_200_90.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_250_100_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_250_100.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_250_110_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_250_110.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_250_120_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_250_120.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_250_130_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_250_130.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_250_140_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_250_140.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_250_150_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_250_150.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_250_160_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_250_160.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_250_170_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_250_170.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_250_180_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_250_180.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_250_190_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_250_190.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_250_1_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_250_1.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_250_200_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_250_200.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_250_210_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_250_210.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_250_220_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_250_220.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_250_230_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_250_230.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_250_235_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_250_235.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_250_240_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_250_240.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_250_243_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_250_243.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_250_25_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_250_25.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_250_50_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_250_50.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_250_75_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_250_75.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_300_100_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_300_100.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_300_125_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_300_125.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_300_150_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_300_150.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_300_160_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_300_160.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_300_170_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_300_170.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_300_180_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_300_180.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_300_190_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_300_190.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_300_1_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_300_1.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_300_200_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_300_200.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_300_210_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_300_210.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_300_220_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_300_220.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_300_230_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_300_230.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_300_240_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_300_240.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_300_250_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_300_250.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_300_25_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_300_25.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_300_260_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_300_260.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_300_270_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_300_270.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_300_280_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_300_280.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_300_285_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_300_285.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_300_290_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_300_290.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_300_293_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_300_293.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_300_50_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_300_50.root
./MakeReducedNtuple.x -ifile=/Users/crogan/Dropbox/SAMPLES/SOS/signal/TChiWZ_300_75_treeProducerSusyMultilepton_tree.root -ofile=SIG/TChiWZ_300_75.root

